name: Eventora CI/CD Pipeline

on:
  push:
    branches: [production]
  pull_request:
    types: [closed]
    branches: [production]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag like v1.0.0'
        required: true
        default: 'v1.0.0'